return { }
-- return {
--   'quarto-dev/quarto-nvim',
--   dependencies = {
--     'jmbuhr/otter.nvim',
--     'jay-babu/mason-nvim-dap.nvim'
--   },
--   config = function()
--     require('mason-nvim-dap').setup {
--       debug = false,
--       closePreviewOnExit = true,
--       lspFeatures = {
--         enabled = true,
--         languages = { 'r', 'python', 'julia', 'bash' },
--         chunks = 'curly', -- 'curly' or 'all'
--         diagnostics = {
--           enabled = true,
--           triggers = { "BufWritePost" }
--         },
--         completion = {
--           enabled = true,
--         },
--       },
--       keymap = {
--         hover = 'K',
--         definition = 'gd',
--         rename = '<leader>lR',
--         references = 'gr',
--       }
--     }
--   end
-- }
